### ISSUE TITLE
[Enhancement] JSON Metrics output

### ISSUE THREAD

**Issue by apeltzer** [grenaud/schmutzi#11]
Hi Gabriel!

would it be possible to add JSON metrics output to allow for tools such as MultiQC to add results from Schmutzi more easily to their report? I've added this to multiple of my tools and found it to be extremely easy then to pass log/metrics to other tools, which could make it more easy to get the tool used in pipelines :-) 

Example code to read the file for Damageprofiler here: https://github.com/ewels/MultiQC/blob/a946dc103c3dd45ccadb8785997691e5e66ac052/multiqc/modules/damageprofiler/damageprofiler.py#L100 

So could be similarly easy to add schmutzi once this is there - and I bet lots of people would love to see this :-)

**Comment by grenaud** [comment]
Yes! I will put it on the TODO list for this week. I will also work on the bioconda packaging.

**Comment by grenaud** [comment]
@apeltzer 3 years later I realize that I did not implement this. This is going to be mean but I will decline to implement this as I am a bit swamped at the moment :-)

**Comment by apeltzer** [comment]
We all are, no offense taken here - hope all is well! Cheers
