### ISSUE TITLE
Schmutzi compilation issue

### ISSUE THREAD

**Issue by ywakiyama** [grenaud/schmutzi#14]
Hello,
I'm trying to install schmutzi and I am getting the following error:

`make -C src/`
`/usr/bin/g++   -o endoCaller ../lib/libgab//libgab.a ../lib/libgab//ReconsReferenceBAM.o endoCaller.o miscfunc.o ../lib/libgab/gzstream/libgzstream.a ../lib/bamtools//build/src/utils/CMakeFiles/BamTools-utils.dir/*cpp.o  ../lib/bamtools//build/src/api/libbamtools.a -lpthread -lm -lz`
`ld: archive has no table of contents file '../lib/libgab//libgab.a' for architecture x86_64`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make[1]: *** [endoCaller] Error 1`
`make: *** [src/endoCaller] Error 2`

Could you please help me to fix this issue?

Thank you,
Yoshiki

**Comment by grenaud** [comment]
Dear Yoshiki,
Thank you for your interest in our method! Can you try going in the root directory and do:
`rm -rfv lib/bamtools/*`
`rm -rfv lib/libgab/*`
`make`
can you also temm me your OS+CPU type? please do a 
`uname -a`
and
`lsb_release -a`

**Comment by ywakiyama** [comment]
Thank you for your quick response.
After removing bamtools and libgab, the installation went well!
test running went well, too.

OS+CPU type is here.
`(base) yoshikiwakiyama@Yoshikis-MacBook-Pro ~ % uname -a`
`Darwin Yoshikis-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`
`(base) yoshikiwakiyama@Yoshikis-MacBook-Pro ~ % sw_vers`
`ProductName:	Mac OS X`
`ProductVersion:	10.15.7`
`BuildVersion:	19H2`

Thank you.

**Comment by grenaud** [comment]
perfect! can I close the issue?

**Comment by ywakiyama** [comment]
Yes!
