### ISSUE TITLE
issue with install for libgap

### ISSUE THREAD

**Issue by TaurVil** [grenaud/schmutzi#15]
Hello, during the installation process I'm running `make` but encounter an error with intalling libgap. In particular, it appears libgap is looking for samtools at `../` from `schmutzi/lib/libgab`, but only `bamtools` and `libgap` are in the folder. I already have samtools installed and available from the path; can I modify this to use that instead?

**Comment by grenaud** [comment]
on which OS are you?

**Comment by TaurVil** [comment]
I'm working on a linux server. With the help of our IT team, I actually found the problem was some additional modules that produce conflicts and I'm able to execute at least contDeam.pl. 

I still get a warning that samtools isn't found, but it turns out that isn't a terminal error like I thought it was
```
make[3]: Leaving directory `/programs/schmutzi/lib/libgab'
Warning: samtools not found`
```

Thanks for the speedy response!

**Comment by grenaud** [comment]
Yes that is not an error message it is just a warning :-)
