### ISSUE TITLE
make:error

### ISSUE THREAD

**Issue by ffontani** [grenaud/schmutzi#16]
Hi Gabriel, 

I am facing issues in compiling the Makefile. 

`
make[4]: *** [src/api/CMakeFiles/BamTools.dir/build.make:244: src/api/CMakeFiles/BamTools.dir/internal/bam/BamMultiReader_p.cpp.o] Error 1
make[3]: *** [CMakeFiles/Makefile2:318: src/api/CMakeFiles/BamTools.dir/all] Error 2
make[2]: *** [Makefile:136: all] Error 2
make[1]: *** [Makefile:26: ../lib/bamtools//build/src/api/libbamtools.a] Error 2
make: *** [Makefile:16: src/endoCaller] Error 2
`

I have been a long time user of schmutzi, and this is the first time I face this kind of problem. Can you help me figuring out what's the matter?
(Below is the complete error message, just to make this issue as clean as possible).

[schmutzi_compile_error.txt](https://github.com/grenaud/schmutzi/files/9940206/schmutzi_compile_error.txt)

Thx!

**Comment by jkimsis** [comment]
Hi, I have the same problem with a different program from Gabriel, discribed [here](https://github.com/grenaud/deML/issues/14). Seems like a problem with a too new g++ version.

**Comment by grenaud** [comment]
hello! I am currently on paternity leave, I should be able to address this
in a week or 2.

**Comment by ffontani** [comment]
> Hi, I have the same problem with a different program from Gabriel, discribed [here](https://github.com/grenaud/deML/issues/14). Seems like a problem with a too new g++ version.

Yeah, it actually runs when compiled with an older version of g++ (I have tested it with g++-9 and it works fine). 

Thank you for the tip! I leave this open just in case someone else face the same issue.

**Comment by grenaud** [comment]
My apologies for the super late reply! It builds fine on my machine. I added some static binaries, can you test them?

**Comment by jkimsis** [comment]
The binaries work if I call them as seperate programs, but I'm not sure how to make them work with the Perl wrappers, on which all the tutorial are based.

**Comment by grenaud** [comment]
Normally you should just put the binaries in the src directory and it should work. Let me know if it is not if there is something missing

**Comment by jkimsis** [comment]
Hello, the binaries seem to be working, at least I can run contDeam.pl on the test data, but running schmutzi.pl throws an error - Executable insertSize does not exist.

**Comment by grenaud** [comment]
I have added insertSize.

**Comment by jkimsis** [comment]
Now the error is about countRecords. I think you might need to add binaries for all the .cpp files.

**Comment by grenaud** [comment]
My apologies for the late reply I had gone home for the day. I have added the binary for countRecords.

**Comment by jkimsis** [comment]
That works, but now I'm getting the error that log2freq doesn't exist.
I'm pretty sure that it will require binaries for all the cpp files:
addXACircular.cpp
bam2prof.cpp
contDeam.cpp
countRecords.cpp
damage2profile.cpp
endoCaller.cpp
filterlog.cpp
insertSize.cpp
jointFreqDeaminated.cpp
jointFreqDeaminatedDouble.cpp
log2ConsensusLog.cpp
log2fasta.cpp
log2freq.cpp
logdiff.cpp
logmask.cpp
logs2pos.cpp
miscfunc.cpp
msa2freq.cpp
msa2log.cpp
msa2singlefreq.cpp
mtCont.cpp
subSampleBAM.cpp

**Comment by grenaud** [comment]
I have added all the binaries with log*

**Comment by jkimsis** [comment]
Now it's missing poshap2splitbam

**Comment by grenaud** [comment]
My apologies, create a directory called splitEndoVsCont and put poshap2splitbam as such:
splitEndoVsCont/poshap2splitbam
