### ISSUE TITLE
Use of uninitialized value in exponentiation (**) at [...]/contDeam.pl line 307.

### ISSUE THREAD

**Issue by Ghabry** [grenaud/schmutzi#2]
Hello,

for my input data (sorry, I'm not allowed to share the BAM file) it generates a .cont.deam that ends in the following data:

```
xxx 0.95	-4329.29
xxx 0.955	-4326.37
xxx 0.96	-4323.45
xxx 0.965	-4320.53
xxx 0.97	-4317.62
xxx 0.975	-4314.71
xxx 0.98	-4311.8
xxx 0.985	-4308.89
xxx 0.99	-4305.99
xxx 0.995	-4303.09
```

(The relevant code starts at Line 267 in contDeam.pl)

Which means $maxLi is exactly $#arrayOfValues+1

Later in Line 304 you do:
```pl
  $ih=min($ih+1, $#arrayOfValues+1 );
  my $subsum = 0;
  for(my $i=$il;$i<=$ih;$i++){  
    $subsum += (10**($arrayOfValues[$i]->{'logLS'})); # 307 Uninitialized value
  }
```

Because $ih+1 is in our case exactly $#arrayOfValues+2 the value is bounded to $#arrayOfValues+1 which means that you index outside of the array bounds in the for-loop.
The obvious solution is removing the "+1" from the $#arrayOfValues+1 but I don't really understand what the code does so I'm not sure if this is the correct solution :).

**Comment by Ghabry** [comment]
The same line is also in other files:
```
./schmutzi.pl:106:      $ih=min($ih+1, $#arrayOfValues+1 );
./contOut2ContEstSource.pl:75:      $ih=min($ih+1, $#arrayOfValues+1 );
./contOut2ContEst.pl:75:      $ih=min($ih+1, $#arrayOfValues+1 );
./contDeam.pl:304:  $ih=min($ih+1, $#arrayOfValues+1 );
```

**Comment by grenaud** [comment]
dear Ghabry, thank you for correcting this! I have since changed it in all 4 files you mentioned. Thank you again!

**Comment by grenaud** [comment]
does that fix the problem? if so, let me know and I will close the issue.

**Comment by Ghabry** [comment]
That should fix all issues, will tell you when I encounter another "uninitialized variable" warning. Thanks for the quick response.
