### ISSUE TITLE
Exit code 256 on line 22 of contDeam.pl

### ISSUE THREAD

**Issue by lnpott9** [grenaud/schmutzi#23]
I was able to run contDeam.pl and schmutzi.pl on about 30 files, but I am getting the same error for 2 of them, and the cont.deam output file is not produced:
`Libgab.cpp: destringify() Unable to convert string="-nan"` and
`system  cmd /home/programs/schmutzi/src/contDeam  -deamread -deam5p 60mt_contdeam.endo.5p.prof  -deam3p 60mt_contdeam.endo.3p.prof  -log  60mt_contdeam.cont.deam   60mt_sorted.md.bam failed: 256 at /home/programs/schmutzi/src/contDeam.pl line 22.`

Is this likely a problem with the input bam file?

**Comment by grenaud** [comment]
hello! How many aligned fragments do you have? My guess is that the coverage is very low.

**Comment by lnpott9** [comment]
They both have very low coverage, so that is probably the problem, thank you!
