### ISSUE TITLE
98% contamination

### ISSUE THREAD

**Issue by jkimsis** [grenaud/schmutzi#25]
Hello,

I'm getting a 98% contamination value for one sample (the other samples from the same extraction and library batch are all <4% contamination). I ran mapDamage on the bam files given after the last iteration for both endogenous and contaminant, and both show clear damage patterns, with the supposed contaminant having even higher damage percentages than the endogenous bam. It also doesn't seem like crosscontamination as the sample shows different mtDNA and Y haplogroups than other sample made in the same batch.

Is it possible that the endogenous - contaminant relatioship got inverted? Or can you suggest a more robust method to check if it actually is crosscontamination from the other samples?

**Comment by grenaud** [comment]
Hello! This very likely happens because of the iterative algorithm diverging. If the resolution of the contaminant is good (because you have adequate frequencies in the database) and the prediction of the endogenous is terrible it will think that everything is contaminant.

This happens a lot at low coverage.

Did you use --notusepredC ?

**Comment by jkimsis** [comment]
I ran it three times with the difference being:
1) with --notusedpredC
2) without --notusepredC
3) ran both contDeam and schmutzi with --lengthDeam 40, and schmutzi without --notusepredC

Every time I got 0.98 0.97 0.99.

The mtDNA coverage is 99,93% with mean depth of 32 (according to samtools coverage).
The full genome coverage is 25% with mean depth of 0.99, but I only ran schmutzi against mtDNA.

**Comment by grenaud** [comment]
that is a bit weird at that depth for the mt, can you please send me the bam file via email?

**Comment by grenaud** [comment]
I did the following:
`samtools index VL8.calmd.bam
`
`
/home/ctools/schmutzi-1.5.6/src/contDeam.pl --library double --length 5  --out  VL8.calmd_out VL8.calmd.bam`

then did:

`/home/ctools/schmutzi-1.5.6/src/schmutzi.pl --t 4 --notusepredC --out  VL8.calmd_out_schmutzi_nopred --uselength --ref /home/databases/genomes/Homo_sapiens/rCRS/rCRS.fa VL8.calmd_out /home/ctools/schmutzi-1.5.6/share/schmutzi/alleleFreqMT/eurasian/freqs/ VL8.calmd.bam
`


I got:
```
cat VL8.calmd_out_schmutzi_nopred_final.cont.est
0.03    0.02    0.04
```

so maybe 3% contamination? The damage profiles look ok
