### ISSUE TITLE
schmutzi.pl failing on line 372 on some BAMs and not others

### ISSUE THREAD

**Issue by lnpott9** [grenaud/schmutzi#26]
Hello! I have been having some problems using schmutzi when using rescaled BAM files vs just deduplicated BAM files (identical in terms of other processing steps like adapter trimming, merging, mapping, etc). I do not get any errors using the deduplicated BAM files, but I do get errors for all but 2 of the files when I use rescaled files (rescaled using mapDamage2). This is an example of the error message:

programs/schmutzi/src/approxDist.R  55mt_schmutzi_npred_1_split_endo.size.gz >  55mt_schmutzi_npred_2_split_endo.size.param failed: 256 at /programs/schmutzi/src/schmutzi.pl line 372.

Is this an issue with the input BAM files themselves or likely another problem?

**Comment by grenaud** [comment]
Hello! can you try running the script in R yourself? This could be a missing library issue.

**Comment by lnpott9** [comment]
It was! Thank you so much!
