### ISSUE TITLE
Problem with wrapper.pl - bam-rewrap doesnt exist anymore

### ISSUE THREAD

**Issue by Weakne55** [grenaud/schmutzi#29]
Hi, in "Recommended workflow for ancient samples" in MT part wrapper.pl is recomended to use for mito reads mapping. This script ask to install bam-rewrap from https://github.com/udo-stenzel/biohazard , but this link doesn`t  exist anymore

**Comment by Weakne55** [comment]
It exist in different repo https://github.com/mpieva/biohazard-tools

**Comment by grenaud** [comment]
modified, thank you!
