### ISSUE TITLE
G++ Compiler Error / Bioconda packaging

### ISSUE THREAD

**Issue by apeltzer** [grenaud/schmutzi#3]
Hi Gabriel,

I'm getting this error when trying to build schmutzi for packaging in bioconda:

``` 
/usr/bin/g++  -o insertSize insertSize.o libgab/utils.o bamtools//build/src/utils/CMakeFiles/BamTools-utils.dir/*cpp.o  bamtools//build/src/api/libbamtools.a -lpthread -lm -lz 
make -C splitEndoVsCont/
make[1]: Entering directory '/home/alex/.conda/envs/condabuild3/conda-bld/schmutzi_1529478894452/work/splitEndoVsCont'
/usr/bin/g++  -lm -O3 -Wall -I../libgab/  -I../libgab//gzstream/ -I../bamtools//include/  -I../bamtools//src/ -c poshap2splitbam.cpp
/usr/bin/g++  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/alex/.conda/envs/condabuild3/conda-bld/schmutzi_1529478894452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib -L/home/alex/.conda/envs/condabuild3/conda-bld/schmutzi_1529478894452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib -o poshap2splitbam poshap2splitbam.o ../libgab/utils.o ../libgab//gzstream/libgzstream.a ../bamtools//build/src/utils/CMakeFiles/BamTools-utils.dir/*cpp.o  ../bamtools/build/src/api/libbamtools.a -lm -lz
make[1]: Leaving directory '/home/alex/.conda/envs/condabuild3/conda-bld/schmutzi_1529478894452/work/splitEndoVsCont'
/usr/bin/g++  -lm -O3 -Wall -Ilibgab/ -Ilibgab//gzstream/ -Ibamtools//include/  -Ibamtools//src/ -c logs2pos.cpp
/usr/bin/g++  -o logs2pos libgab/utils.o logs2pos.o libgab/gzstream/libgzstream.a bamtools//build/src/utils/CMakeFiles/BamTools-utils.dir/*cpp.o  bamtools//build/src/api/libbamtools.a -lpthread -lm -lz -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/alex/.conda/envs/condabuild3/conda-bld/schmutzi_1529478894452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib -L/home/alex/.conda/envs/condabuild3/conda-bld/schmutzi_1529478894452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib
/usr/bin/g++  -lm -O3 -Wall -Ilibgab/ -Ilibgab//gzstream/ -Ibamtools//include/  -Ibamtools//src/ -c countRecords.cpp
countRecords.cpp: In function ‘int main(int, char**)’:
countRecords.cpp:22:10: warning: variable ‘onlyMapped’ set but not used [-Wunused-but-set-variable]
     bool onlyMapped=false;
          ^~~~~~~~~~
/usr/bin/g++  -o countRecords countRecords.o libgab/utils.o bamtools//build/src/utils/CMakeFiles/BamTools-utils.dir/*cpp.o  bamtools//build/src/api/libbamtools.a -lpthread -lm -lz 
/usr/bin/g++  -lm -O3 -Wall -Ilibgab/ -Ilibgab//gzstream/ -Ibamtools//include/  -Ibamtools//src/ -c jointFreqDeaminated.cpp
/usr/bin/g++  -o jointFreqDeaminated jointFreqDeaminated.o libgab/utils.o libgab//ReconsReferenceBAM.o bamtools//build/src/utils/CMakeFiles/BamTools-utils.dir/*cpp.o  bamtools//build/src/api/libbamtools.a -lpthread -lm -lz 
/usr/bin/g++  -lm -O3 -Wall -Ilibgab/ -Ilibgab//gzstream/ -Ibamtools//include/  -Ibamtools//src/ -c jointFreqDeaminatedDouble.cpp
/usr/bin/g++  -o jointFreqDeaminatedDouble jointFreqDeaminatedDouble.o libgab/utils.o libgab//ReconsReferenceBAM.o bamtools//build/src/utils/CMakeFiles/BamTools-utils.dir/*cpp.o  bamtools//build/src/api/libbamtools.a -lpthread -lm -lz 
/usr/bin/g++  -lm -O3 -Wall -Ilibgab/ -Ilibgab//gzstream/ -Ibamtools//include/  -Ibamtools//src/ -c msa2log.cpp
msa2log.cpp: In function ‘int main(int, char**)’:
msa2log.cpp:72:41: error: parameter may not have variably modified type ‘std::__cxx11::string [(argc + -2)]’ {aka ‘std::__cxx11::basic_string<char> [(argc + -2)]’}
     FastQParser fqp (string(argv[argc-2]),true );
                                         ^
make: *** [Makefile:152: msa2log.o] Error 1
```
Any idea why? 

Found ways to get things working, but that one seems to be something in the code that needs (?) to be fixed for the GCC compiler to get it running again. 

Just referencing my PR for bioconda-recipes https://github.com/bioconda/bioconda-recipes/pull/9477

**Comment by apeltzer** [comment]
Also holds true locally - seems to be one of the typical compiler flags that are now more strictly checking code

**Comment by grenaud** [comment]
Hi Alex, it seems this a problem with older version of the compiler. I changed the line to:
    string fqfilename = string(argv[argc-2]);
    FastQParser fqp (fqfilename,true );

Does it work now?

**Comment by apeltzer** [comment]
Locally it does - however, the bioconda recipes should be splitted, e.g.:

- bamtools should be modular, e.g. I should be able to work with the system-wide bamtools installation (libbamtools.a) instead of pulling & directly building this in schmutzi

Can you maybe allow for that via a variable in the libgab dependency that is pulled during make? 
I can patch the main makefile to use a system wide installation, but not that easily the libgab Makefile. 

See this PR for the problem-happy to help here too!

https://github.com/bioconda/bioconda-recipes/pull/9477/files

**Comment by apeltzer** [comment]
Sorry this seems to be quite complicated, but I'd love to have schmutzi packaged that way and make it work e.g. in Docker/Singularity easily...

**Comment by grenaud** [comment]
Sure! But what about the char * being cast as a string? Does it compile now?

Alexander Peltzer <notifications@github.com> schrieb am Fr., 22. Juni 2018
13:42:

**Comment by apeltzer** [comment]
Tested a up2date git clone of the current repository - works fine for me :-) 
(both on gcc8.1 and 7.2)

**Comment by grenaud** [comment]
Perfect, I will check the bioconda issue. Would passing the path to
bamtools directly to make work? Is it known in advance?

Gabriel

Alexander Peltzer <notifications@github.com> schrieb am Fr., 22. Juni 2018
15:06:

**Comment by apeltzer** [comment]
Yeah I guess we can close this one here and continue in the bioconda pull request then. Yes, its known - we can specify e.g. a variable `BAMTOOLSPATH=......` and use that in the Makefile. So probably you just need to make it possible to use such a variable (and similar to gcc, so it doesn't only look in `/usr/bin/gcc`). 

You can also have a look at my attempt in the PR https://github.com/bioconda/bioconda-recipes/pull/9477 (`Makefile.patch`) to see what I'm trying there. We just need to have a possibility to call directly the compiler(s) and libraries inside the conda environment.
