### ISSUE TITLE
Incorrect order of actions in Recommended workflow for ancient samples

### ISSUE THREAD

**Issue by Weakne55** [grenaud/schmutzi#30]
It says:
vii.Run schmutzi.pl once with default parameters
viii.Run schmutzi.pl again with "--usepredC"

But schmutzi.pl doesn't have --usepredC option. Only --notusepredC
should this plan be changed as follows:
vii.Run schmutzi.pl once with "--notusepredC"
viii.Run schmutzi.pl again with default parameters ?

**Comment by grenaud** [comment]
thanks for the input!! I changed the readme and make some minor spelling correction as well.
