### ISSUE TITLE
Incorrect path to poshap2splitbam in schmutzi.pl

### ISSUE THREAD

**Issue by antmarge** [grenaud/schmutzi#4]
Line 445 of schmutzi.pl checks if the poshap2splitbam executable exists in  `path/to/schmutzi/src/` when it actually exists in `path/to/schmutzi/src/splitEndoVsCont/`. Thus an error is produced:

> Executable path/to/schmutzi/src/poshap2splitbam does not exist

Editing the line to include the correct file path fixes the problem.

**Comment by grenaud** [comment]
Dear Margaret, thank you very much for raising this issue! The line now reads:

`if(!doesFileExists(\$splitEndo)){`
 ` $splitEndo  = $pathdir."/poshap2splitbam";`
`}`


I want it to first look in src/splitEndoVsCont, then in src/. This was done to accomate make install.

Let me know if this works and if I can close the issue.
