### ISSUE TITLE
197 Contaminant database

### ISSUE THREAD

**Issue by antmarge** [grenaud/schmutzi#6]
What's in the 197 contaminant database in `schmutzi/share/schmutzi/alleleFreqMT/197/freqs`. Could not find documentation for this anywhere. Thanks!

**Comment by grenaud** [comment]
I added the following to the README:

> 
> 
> - What is share/schmutzi/alleleFreqMT/197/freqs/
> 
>   This is a very small putative contaminant database of 197 human mitogenomes using a worldwide sampling. For samples collected in Eurasia, we recommend the eurasian/ database. However, this database might be better if you suspect that your contaminant is African in origin. As ancient DNA only expanded into Africa relatively recently, we are currently making a more comprehensive curated mitogenome database with a worldwide distribution.

As stated, I am currently compiling a more extensive database. But feel free to use the 197 if you think your mitogenome might be African in origin.
