### ISSUE TITLE
Schmutzi compilation issue with gcc 7.3.0

### ISSUE THREAD

**Issue by cwjeong** [grenaud/schmutzi#7]
Upon trying to compile schmutzi with gcc 7.3.0, I got a large amount of error messages like this:

...
BamReader_p.cpp:(.text+0x522): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)'
BamReader_p.cpp:(.text+0x535): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*, unsigned long)'
BamReader_p.cpp:(.text+0x546): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*, unsigned long)'
...

Switching to gcc v4.8.5 and starting over from the scratch, schmutzi compilation went well.

**Comment by grenaud** [comment]
Dear Choongwon, Thank you for reporting this along with the fix. I plan on removing bamtools from my programs as it seems to be no longer maintained.

Thank you!

**Comment by grenaud** [comment]
Dear Choongwon, Thank you for reporting this along with the fix. I plan on removing bamtools from my programs as it seems to be no longer maintained.

Thank you!
