### ISSUE TITLE
Query reference base is not the same for read ... after samtools calmd

### ISSUE THREAD

**Issue by ma-diroma** [grenaud/schmutzi#9]
Hi,
I had the error "Query reference base is not the same for read ..." for my BAM file, which contains only mitochondrial reads mapped to hg19+rCRS. So I launched samtools calmd 
```
samtools calmd -b file.bam reference.fasta > output.MD.bam
samtools index output.MD.bam
```
and relaunched schmutzi, but the error remained the same.

`Query reference base is not the same for read M_A00619:51:HH7VYDRXX:1:2258:7003:30154C pos 1`

I checked the position, the reference base corresponded to the same base in my read so I can't understand where the issue is. I tried to remove that read, but then the same type of error was related to another read.
Please find attached the (partial) content of my log file, I hope you could help me.

```
reading the contamination estimate file: test_contDeam_rescaled_filtered_out_1_cont.est



############################
#    ITERATION #  1        #
#                          #
# Contamination rate: 0.07 #
############################
running cmd /opt/schmutzi/schmutzi/endoCaller  -seq test_contDeam_rescaled_filtered_out_1_endo.fa   -log test_contDeam_rescaled_filtered_out_1_endo.log  -name MT  -qual 0  -logindel 50  -deamread  -deam5p test_contDeam_rescaled_filtered_out_1_endo.5p.prof  -deam3p test_contDeam_rescaled_filtered_out_1_endo.3p.prof  -cont 0.075  -deam5pc test_contDeam_rescaled_filtered_out_1_cont.5p.prof  -deam3pc test_contDeam_rescaled_filtered_out_1_cont.3p.prof  -single   -seqc test_contDeam_rescaled_filtered_out_1_cont.fa   -logc test_contDeam_rescaled_filtered_out_1_cont.log  -namec MTc  -l 16569  /home/cvergata/Desktop/refs/hg_19_dbSNP_1-4-19/Homo_sapiens_assembly19_500.fasta Pol-10_S24_L001_R1_001.fastq.merged.fq.gz.fq.MT_realigned.bam.mapped.bam.sorted.bam.cleaned_rmdup.bam.sorted.bam_MT_q1_filtered.bam.MD.bam 
1	G	M	G	G	R=N	C=G	M_A00619:51:HH7VYDRXX:1:2258:7003:30154C
0	M	0
1	M	1
2	M	2
3	C	3
4	M	4
5	M	5
6	M	6
7	M	7
8	M	8
9	M	9
10	M	10
11	M	11
12	M	12
13	M	13
14	M	14
15	M	15
16	M	16
17	M	17
18	M	18
19	M	19
20	M	20
21	M	21
22	M	22
23	M	23
24	M	24
25	M	25
26	M	26
27	M	27
28	M	28
29	M	29
30	M	30
31	M	31
32	M	32
33	M	33
34	M	34
35	M	35
36	M	36
37	M	37
38	M	38
39	M	39
40	M	40
41	M	41
42	M	42
43	M	43
44	M	44
45	M	45
46	M	46
47	M	47
48	M	48
49	M	49
50	M	50
51	M	51
52	M	52
53	M	53
54	M	54
55	M	55
56	M	56
57	M	57
58	M	58
59	M	59
60	M	60
61	M	61
62	M	62
63	M	63
64	M	64
65	M	65
66	M	66
67	M	67
68	M	68
69	M	69
70	M	70
71	M	71
72	M	72
73	M	73
74	M	74
75	M	75
76	M	76
77	M	77
78	M	78
79	M	79
80	M	80
81	M	81
82	M	82
83	M	83
84	M	84
85	M	85
86	M	86
87	M	87
88	M	88
89	M	89
90	M	90
91	M	91
92	M	92
93	M	93
94	M	94
95	M	95
96	M	96
97	M	97
98	M	98
99	M	99
100	M	100
101	M	101
102	M	102
103	M	103
104	M	104
105	M	105
106	M	106
107	M	107
108	M	108
109	M	109
110	M	110
111	M	111
112	M	112
113	M	113
114	M	114
115	M	115
116	M	116
117	M	117
118	M	118
119	M	119
120	M	120

```
Best wishes,
Maria Angela

**Comment by grenaud** [comment]
Dear Maria, my apologies for the delay in replying. I was very sick in March, presumably COVID19, had grants that were due and now I'm plowing through the unanswered emails. Could you send me via email the bam file that is causing this?

**Comment by ma-diroma** [comment]
Don't worry, there is no rush. I hope you and your family are well now. 
Is this your email? gabre@dtu.dk

Thanks for your help, I really appreciate it.
Best wishes,
Maria Angela

**Comment by grenaud** [comment]
yes it is.

**Comment by grenaud** [comment]
Dear Maria,
Did you have time to send me the bam file, I still have you on my todo list
;-)

Gabriel

**Comment by ma-diroma** [comment]
Hi Gabriel,

we have already solved! Thank you for your help :)

Maria Angela

**Comment by alexandregilardet** [comment]
Hi, 
I'm encountering the same issue, would you please be able to share your workaround? 
Thanks a lot,
Alexandre

**Comment by ma-diroma** [comment]
Hi,

I was just using a wrong reference sequence. You have to map reads to rCRS.

BW
Maria Angela

**Comment by alexandregilardet** [comment]
Thanks for the quick answer. Do you mean that mapping against a whole-genome reference and then extracting only the MT reads in a new BAM before to calmd and run schmutzi is not possible?

**Comment by ma-diroma** [comment]
Yes, that was causing my error

**Comment by grenaud** [comment]
> Thanks for the quick answer. Do you mean that mapping against a whole-genome reference and then extracting only the MT reads in a new BAM before to calmd and run schmutzi is not possible?

@alexandregilardet  I would advise against this, this can cause massive gaps in the alignment to the MT due to NUMTs.
